### ISSUE TITLE
Float16 NaN and infinity are handled incorrectly

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#10]
Expected result:

```yaml
[uavcan.equipment.hardpoint.Status]
# Received struct ts_m=126159.735617 ts_utc=1448947534.085266 snid=125
hardpoint_id: 7
payload_weight: nan
payload_weight_variance: inf
status: 0
```

Actual result:

```
uavcan.equipment.hardpoint.Status(hardpoint_id=7, payload_weight=131008.0, payload_weight_variance=65536.0, status=0)
```
