### ISSUE TITLE
Incorrect decoding of float16

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#21]
CAN frames:

```
RX    14:34:43.053642    1004277D    85 AD 00 00 00 00 00 92     ........    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.053643    1004277D    00 00 F3 F8 DD E9 27 32     ......'2    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.053644    1004277D    4B 05 40 00 1B F8 67 12     K.@...g.    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.053644    1004277D    CD E0 01 D6 A3 6A 58 32     .....jX2    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.053644    1004277D    72 61 C0 C0 52 A0 18 12     ra..R...    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.054628    1004277D    BA B5 DD 28 D1 B6 1F 32     ...(...2    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.054629    1004277D    00 06 7A 4E 7A 4E C9 12     ..zNzN..    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.055632    1004277D    4E B3 39 B3 39 B3 39 32     N.9.9.92    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.055633    1004277D    4D 41 CC CC CC 3E EB 12     MA...>..    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.055633    1004277D    51 B8 3E 99 99 19 3E 32     Q.>...>2    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.055634    1004277D    A8 88 47 AA 08 A4 DA 12     ..G.....    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.055634    1004277D    E8 30 0E 57 52 38 10 32     .0.WR8.2    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.056645    1004277D    06 A0 52 A0 52 A0 52 12     ..R.R.R.    125        uavcan.equipment.gnss.Fix2
RX    14:34:43.056646    1004277D    A5 39 A5 39 A5 39 72        .9.9.9r     125        uavcan.equipment.gnss.Fix2
```

Properly decoded message (using libuavcan):

```yaml
timestamp: 
  usec: 0
gnss_timestamp: 
  usec: 1490009682999539
gnss_time_standard: 2
num_leap_seconds: 27
longitude_deg_1e8: 3771557880
latitude_deg_1e8: 5560456250
height_ellipsoid_mm: 231369
height_msl_mm: 218122
ned_velocity: [-0.35791, 0.0379944, -0.426025]
sats_used: 7
status: 3
mode: 0
sub_mode: 0
covariance: [25.9062, 25.9062, 27.1406, 0.712402, 0.712402, 0.712402]
pdop: 2.65039
ecef_position_velocity: 
  - 
    velocity_xyz: [0.4, 0.36, 0.15]
    position_xyz_mm: [2856814760, 2209238410, 5239887630]
    covariance: [53, 53, 53, 0.705566, 0.705566, 0.705566]
```

PyUAVCAN output:

```yaml
timestamp: 
  usec: 0 # UNKNOWN
gnss_timestamp: 
  usec: 1490009682999539
gnss_time_standard: 2 # UTC
num_leap_seconds: 27
longitude_deg_1e8: 3771557880
latitude_deg_1e8: 5560456250
height_ellipsoid_mm: 231369
height_msl_mm: 218122
ned_velocity: [-0.3579, 0.0380, -0.4260]
sats_used: 7
status: 3 # 3D_FIX
mode: 0 # SINGLE
sub_mode: 0
covariance: [25.9062, 25.9062, 27.1406, 0.7124, 0.7124, 0.7124]
pdop: 2.6504
ecef_position_velocity: 
  - 
    velocity_xyz: [0.400000, 0.360000, 0.150000]
    position_xyz_mm: [2856814760, 2209238410, 5239887630]
    covariance: [-0.0000, -0.0000, -0.0000, -0.0010, -0.0012, -0.0012]
```

Notice that the last `covariance` field contains incorrect data.

Data type definition: https://github.com/UAVCAN/dsdl/tree/a7d19e2a07a0d3e2651fb80e60945d6b2bb7b296/uavcan/equipment/gnss
